Apis/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path('book/cart/',CartView.as_view() ,name='book_cart'),
   

    ]

BookStore/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()
admin.site.enable_nav_sidebar = False

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('', include('Users.urls')),
    path('', include('Apis.urls')),
    path('', include('payment_gateway.urls')),



] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Users/models.py
#standerd imports
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.db.models.signals import post_save
from django.dispatch import receiver
from Apis import models as mp 





class CustomUserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""


    def _create_user(self, email, password=None, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)

#  customize default user model as CustomUser
class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    phone=models.CharField(max_length=13,null=True,blank=True, unique=True)

    objects = CustomUserManager()
    def get_full_name(self):
        return self.first_name+" "+self.last_name
    def get_total_cart(self):
        items=mp.CartItems.objects.filter(user=self)
        return items.count()

class Profile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    dob = models.DateField(null=True, blank=True)
    country=models.TextField(blank=True, null=True)
    state=models.TextField(blank=True, null=True)
    PAddress=models.TextField(blank=True,null=True)
    street=models.CharField(max_length=100,blank=True,null=True)
    zipcode=models.CharField(max_length=7,blank=True,null=True)
    added = models.DateTimeField(auto_now_add=True,blank=True,null=True)
    updated = models.DateTimeField(auto_now=True,blank=True,null=True)
    profile=models.ImageField(upload_to ='Mentor_profiles/',default='default/profile.png',null=True, blank=True)


    def __str__(self):  # __unicode__ for Python 2
        return self.user.get_full_name()

@receiver(post_save, sender=CustomUser)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

store/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.utils import timezone
from Users.models import CustomUser


class Author(models.Model):
    first_name = models.CharField(max_length = 100)
    last_name = models.CharField(max_length = 100)
    added = models.DateTimeField(auto_now_add=True,blank=True,null=True)
    updated = models.DateTimeField(auto_now=True,blank=True,null=True)

    def __str__(self):
        return "%s, %s" % (self.last_name, self.first_name)


class Publisher(models.Model):
    name = models.CharField(max_length = 100)
    added = models.DateTimeField(auto_now_add=True,blank=True,null=True)
    updated = models.DateTimeField(auto_now=True,blank=True,null=True)


def cover_upload_path(instance, filename):
    return '/'.join(['books', str(instance.id), filename])

class genres(models.Model):
    name=models.CharField(max_length = 200)
    added = models.DateTimeField(auto_now_add=True,blank=True,null=True)
    updated = models.DateTimeField(auto_now=True,blank=True,null=True)
    def __str__(self):
        return self.name
    def get_book_count(self):
        return self.books.all().count()


class Book(models.Model):
    isbn = models.CharField(max_length = 200)
    title = models.CharField(max_length = 200)
    author = models.ForeignKey(Author,on_delete=models.CASCADE)
    publisher=models.ForeignKey(Publisher,on_delete=models.CASCADE)
    description = models.TextField()
    publish_date = models.DateField(default = timezone.now)
    price = models.DecimalField(decimal_places=2, max_digits=8)
    stock = models.IntegerField(default=0)
    edition = models.IntegerField(default=0)
    cover_image = models.ImageField(upload_to=cover_upload_path, default='books/empty_cover.jpg')
    genre=models.ManyToManyField(genres,through='book_genres',related_name='books')
    added = models.DateTimeField(auto_now_add=True,blank=True,null=True)
    updated = models.DateTimeField(auto_now=True,blank=True,null=True)
    def __str__(self):
        return self.title
    def get_genre(self):
        all_gen=''
        q=self.genre.all()
        for i in range(len(q)):
            if i == len(q)-1:
                all_gen+=q[i].name
            else:
                all_gen+=q[i].name+" ,"
        return all_gen


class book_genres(models.Model):
    book = models.ForeignKey(Book,on_delete=models.CASCADE)
    genre=models.ForeignKey(genres,on_delete=models.CASCADE)
    added = models.DateTimeField(auto_now_add=True,blank=True,null=True)
    updated = models.DateTimeField(auto_now=True,blank=True,null=True)


class Review(models.Model):
    book = models.ForeignKey(Book,on_delete=models.CASCADE)
    customer = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    publish_date = models.DateField(default = timezone.now)
    text = models.TextField()
    rate = models.IntegerField(default=0)
    added = models.DateTimeField(auto_now_add=True,blank=True,null=True)
    updated = models.DateTimeField(auto_now=True,blank=True,null=True)



class Discount(models.Model):
    customer=models.ManyToManyField(CustomUser,related_name='books')
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    rate= models.IntegerField()
    name= models.CharField(max_length = 200)


class RazorPayDetails(models.Model): 
    razorpay_payment_id=models.CharField(max_length=250,null=True,blank=True)
    razorpay_order_id=models.CharField(max_length=250,null=True,blank=True)
    razorpay_signature=models.CharField(max_length=250,null=True,blank=True)
    added = models.DateTimeField(auto_now_add=True,blank=True,null=True)
    updated = models.DateTimeField(auto_now=True,blank=True,null=True)


class Order(models.Model):
    customer = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    price = models.IntegerField(null=True)
    date= models.DateTimeField(auto_now=True,blank=True,null=True)
    order_curruncy=models.CharField(max_length=100,null=True,blank=True)
    status = models.BooleanField(default=False)
    razorpay = models.ForeignKey(RazorPayDetails, on_delete=models.CASCADE,null=True,blank=True)
    discounts = models.ForeignKey(Discount, on_delete=models.CASCADE,null=True,blank=True)



    def add_to_cart(self, book_id):
        book = Book.objects.get(pk=book_id)
        try:
            preexistting_order = BookOrder.objects.get(book=book, cart=self)
            preexistting_order.quantity +=1
            preexistting_order.save()
        except BookOrder.DoesNotExist:
            new_order = BookOrder.objects.create(
                book = book,
                cart = self,
                quantity = 1
            )

    def remove_from_cart(self, book_id):
        book = Book.objects.get(pk=book_id)
        try:
            preexistting_order = BookOrder.objects.get(book=book, cart=self)
            if preexistting_order.quantity > 1:
                preexistting_order.quantity -=1
                preexistting_order.save()
            else:
                preexistting_order.delete()
        except BookOrder.DoesNotExist:
            pass


class BookOrder(models.Model):
    book = models.ForeignKey(Book,on_delete=models.CASCADE)
    order = models.ForeignKey(Order,on_delete=models.CASCADE)
    quantity = models.IntegerField()
    amount = models.IntegerField()



class Category(models.Model):
    name=models.CharField(max_length=100,null=True,blank=True)

    

Users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ObjectDoesNotExist
from django.core.exceptions import ValidationError
from .models import CustomUser
class SignUpForm(forms.ModelForm):
    email = forms.EmailField(required=True)
    password1 = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = CustomUser
        fields = ("email", "password1", "password2",'first_name','last_name','phone')

    def save(self, commit=True):
        user = super(SignUpForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        user.username=self.cleaned_data["email"]
        user.first_name=self.cleaned_data["first_name"]
        user.last_name=self.cleaned_data["last_name"]
        user.phone=self.cleaned_data["phone"]

        user.set_password(self.cleaned_data["password1"])

        if commit:
            user.save()
        return user
    
    def clean(self):
        form_data = self.cleaned_data
        email=form_data.get("email")
        phone=form_data.get("phone")


        try:
            user_e=CustomUser.objects.get(email=email)

        except:
            user_e=None

        try:
            user_p=CustomUser.objects.get(phone=phone)

        except:
            user_p=None
        if user_e:
            raise ValidationError("email is already exist")
        if user_p:
            raise ValidationError("Phone number is already exist")

        password1 = form_data.get("password1")
        password2 = form_data.get("password2")
        if password1 != password2:
            raise ValidationError("Passwords did not match")
        return form_data

templates/Landing_page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main>
    <section class="section-1">
      <div class="container text-center">
        <div class="row">
          <div class="col-md-6 col-12">
            <div class="pray">
              <img src="{% static 'img/assets/pexels-photo-1904769.jpeg'%}" alt="Pray" class="" />
            </div>
          </div>
          <div class="col-md-6 col-12">
            <div class="panel text-left">
              <h1>Mr. Devid Smith</h1>
              <p class="pt-4">
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Facere iure adipisci harum ducimus accusantium, repudiandae aperiam
                voluptatum, id ex ratione omnis reiciendis possimus officiis.
              </p>
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi vitae, tenetur quidem eum aliquid vel labore sint placeat
                ad deserunt consectetur fugit ullam. Eius unde neque ducimus obcaecati ipsum quos vero totam recusandae hic
                expedita nemo sit, illum harum. Quisquam impedit ullam itaque facere et ad molestiae quod reprehenderit excepturi!
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
   
    <section class="section-4">
        <div class="container text-center">
          <h1 class="text-dark">What our Reader's Say about us</h1>
          <p class="text-light">Lorem ipsum dolor sit amet.</p>
        </div>
        <div class="team row ">
          <div class="col-md-4 col-12 text-center">
              <div class="card mr-2 d-inline-block shadow-lg">
                  <div class="card-img-top">
                    <img src="{% static 'img/assets/UI-face-3.jpg'%}" class="img-fluid border-radius p-4" alt="">
                  </div>
                  <div class="card-body">
                    <h3 class="card-title">Blalock Jolene</h3>
                    <p class="card-text">
                      Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint iure autem recusandae, veniam, illo dolor soluta assumenda
                      minima quia velit officia sit exercitationem nam ipsa, repellendus aut facilis quasi voluptas!
                    </p>
                    <a href="#" class="text-secondary text-decoration-none">Go somewhere</a>
                    <p class="text-black-50">CEO at Google</p>
                  </div>
                </div>
          </div>
          <div class="col-md-4 col-12">
              <div id="carouselExampleControls" class="carousel slide " data-ride="carousel">
                  <div class="carousel-inner text-center">
                    <div class="carousel-item active">
                      <div class="card mr-2 d-inline-block shadow">
                        <div class="card-img-top">
                          <img src="{% static 'img/assets/UI-face-1.jpg'%}" class="img-fluid rounded-circle w-50 p-4" alt="">
                        </div>
                        <div class="card-body">
                          <h3 class="card-title">Allen Agnes</h3>
                          <p class="card-text">
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint iure autem recusandae, veniam, illo dolor soluta assumenda
                            minima quia velit officia sit exercitationem nam ipsa, repellendus aut facilis quasi voluptas!
                          </p>
                          <a href="#" class="text-secondary text-decoration-none">Go somewhere</a>
                          <p class="text-black-50">CEO at Google</p>
                        </div>
                      </div>
                    </div>
                    <div class="carousel-item">
                      <div class="card  d-inline-block mr-2 shadow">
                        <div class="card-img-top">
                          <img src="{% static 'img/assets/UI-face-2.jpg'%}" class="img-fluid rounded-circle w-50 p-4" alt="">
                        </div>
                        <div class="card-body">
                          <h3 class="card-title">Amiel Barbara</h3>
                          <p class="card-text">
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint iure autem recusandae, veniam, illo dolor soluta assumenda
                            minima quia velit officia sit exercitationem nam ipsa, repellendus aut facilis quasi voluptas!
                          </p>
                          <a href="#" class="text-secondary text-decoration-none">Go somewhere</a>
                          <p class="text-black-50">CEO at Google</p>
                        </div>
                      </div>
                    </div>
                </div>
          </div>
          </div>
          <div class="col-md-4 col-12 text-center">
              <div class="card mr-2 d-inline-block shadow-lg">
                  <div class="card-img-top">
                    <img src="{% static 'img/assets/UI-face-4.jpg'%}" class="img-fluid border-radius p-4" alt="">
                  </div>
                  <div class="card-body">
                    <h3 class="card-title">Olivia Louis</h3>
                    <p class="card-text">
                      Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint iure autem recusandae, veniam, illo dolor soluta assumenda
                      minima quia velit officia sit exercitationem nam ipsa, repellendus aut facilis quasi voluptas!
                    </p>
                    <a href="#" class="text-secondary text-decoration-none">Go somewhere</a>
                    <p class="text-black-50">CEO at Google</p>
                  </div>
                </div>
          </div>
        </div>
      </section>
    <section class="section-2 container-fluid p-0">
      

      <div class="purchase text-center">
        <h1>Purchase Whatever You Want</h1>
        <p>
          Lorem, ipsum dolor sit amet consectetur adipisicing elit.
        </p>
        <div class="cards">
          <div class="d-flex flex-row justify-content-center flex-wrap">
            <div class="card">
              <div class="card-body">
                <div class="title">
                  <h5 class="card-title">PDF</h5>
                </div>
                <p class="card-text text-light">
                  With supporting text below as a natural lead-in.
                </p>
                <div class="pricing">
                  <h1><span>&#8377;</span> 177</h1>
                  <a href="#" class="btn btn-dark px-5 py-2 primary-btn mb-5">Purchase Now</a>
                </div>
              </div>
            </div>
            <div class="card">
              <div class="card-body">
                <div class="title">
                  <h5 class="card-title">E-book</h5>
                </div>
                <p class="card-text text-light">
                  With supporting text below as a natural lead-in.
                </p>
                <div class="pricing">
                  <h1><span>&#8377;</span> 399</h1>
                  <a href="#" class="btn btn-dark px-5 py-2 primary-btn mb-5">Purchase Now</a>
                </div>
              </div>
            </div>
            <div class="card">
              <div class="card-body">
                <div class="title">
                  <h5 class="card-title">Print Copy</h5>
                </div>
                <p class="card-text text-light">
                  With supporting text below as a natural lead-in.
                </p>
                <div class="pricing">
                  <h1><span>&#8377;</span> 758</h1>
                  <a href="#" class="btn btn-dark px-5 py-2 primary-btn mb-5">Purchase Now</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="cover">
        <div class="overlay"></div>
        <div class="content text-center">
          <h1>Some Features That Made Us Unique</h1>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, eum?
          </p>
        </div>
      </div>
      <div class="container-fluid text-center">
        <div class="numbers d-flex flex-md-row flex-wrap justify-content-center">
          <div class="rect">
            <h1>2345</h1>
            <p>Happy Client</p>
          </div>
          <div class="rect">
            <h1>6784</h1>
            <p>Cups Coffee</p>
          </div>
          <div class="rect">
            <h1>1056</h1>
            <p>Tickets Submitted</p>
          </div>
          <div class="rect">
            <h1>9152</h1>
            <p>Total Projects</p>
          </div>
        </div>
      </div>

    </section>
    <section class="section-3 container-fluid p-0 text-center">
      <div class="row">
        <div class="col-md-12 col-sm-12">
          <h1>Download Our App for all Platform</h1>
          <p>
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eum exercitationem alias perspiciatis omnis quod possimus odit
            voluptatum! Sunt ea quasi praesentium, tenetur doloribus animi obcaecati, sint nemo quae laudantium iusto unde
            eaque nostrum nobis voluptatum
          </p>
        </div>
      </div>
      <div class="platform row">
        <div class="col-md-6 col-sm-12 text-right">
          <div class="desktop shadow-lg">
            <div class="d-flex flex-row justify-content-center text-white">
              <i class="fas fa-desktop fa-3x py-2 pr-3"></i>
              <div class="text text-left">
                <h3 class="pt-1 m-0">Desktop</h3>
                <p class="p-0 m-0">On website</p>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-sm-12 text-left">
          <div class="desktop shadow-lg">
            <div class="d-flex flex-row justify-content-center text-white">
              <i class="fas fa-mobile-alt fa-3x py-2 pr-3"></i>
              <div class="text text-left">
                <h3 class="pt-1 m-0">On Mobile</h3>
                <p class="p-0 m-0">On Play Store</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    
  </main>
{% endblock content %}

templates/signup.html
{% extends 'base2.html'%}
{% load static %}

   {% block style %}
   <style>

        /*
*
* ==========================================
* CUSTOM UTIL CLASSES
* ==========================================
*
*/

.border-md {
    border-width: 2px;
}

.btn-facebook {
    background: #405D9D;
    border: none;
}

.btn-facebook:hover, .btn-facebook:focus {
    background: #314879;
}

.btn-twitter {
    background: #42AEEC;
    border: none;
}

.btn-twitter:hover, .btn-twitter:focus {
    background: #1799e4;
}



/*
*
* ==========================================
* FOR DEMO PURPOSES
* ==========================================
*
*/

body {
    min-height: 100vh;
    background: linear-gradient( 110.1deg,  rgba(34,126,34,1) 2.9%, rgba(168,251,60,1) 90.3% );
}

.form-control:not(select) {
    padding: 1.5rem 0.5rem;
}

select.form-control {
    height: 52px;
    padding-left: 0.5rem;
}

.form-control::placeholder {
    color: #ccc;
    font-weight: bold;
    font-size: 0.9rem;
}
.form-control:focus {
    box-shadow: none;
}

    </style>
    {% endblock style %}
   
    {% block content %}
    
      
      
      <div class="container">
        <div class="row py-1 mt-1 align-items-center text-center">
          <!-- For Demo Purpose -->
          <div class="col-md-5 pr-lg-5 mb-5 mb-md-0 text-white">
            <img src="https://res.cloudinary.com/mhmd/image/upload/v1569543678/form_d9sh6m.svg" alt="" class="img-fluid mb-3 d-none d-md-block">
            <h1>Create an Account</h1>
            <p class="font-italic mb-0">Thanks For being with Us.</p>
           
          </div>
      
          <!-- Registeration Form -->
          <div class="col-md-7 col-lg-6 ml-auto">
            <form action="{% url 'register' %}" method="POST">
            {% csrf_token %}
              <div class="row">
      
                <!-- First Name -->
                <div class="input-group col-lg-6 mb-4">
                  <div class="input-group-prepend">
                    <span class="input-group-text bg-white px-4 border-md border-right-0">
                      <i class="fa fa-user text-muted"></i>
                    </span>
                  </div>
                  <input id="id_first_name" type="text" name="first_name" placeholder="First Name" class="form-control bg-white border-left-0 border-md">
                </div>
      
                <!-- Last Name -->
                <div class="input-group col-lg-6 mb-4">
                  <div class="input-group-prepend">
                    <span class="input-group-text bg-white px-4 border-md border-right-0">
                      <i class="fa fa-user text-muted"></i>
                    </span>
                  </div>
                  <input id="id_last_name" type="text" name="last_name" placeholder="Last Name" class="form-control  border-left-0 border-md">
                </div>
      
                <!-- Email Address -->
                <div class="input-group col-lg-12 mb-4">
                  <div class="input-group-prepend">
                    <span class="input-group-text bg-white px-4 border-md border-right-0">
                      <i class="fa fa-envelope text-muted"></i>
                    </span>
                  </div>
                  <input id="id_email" type="email" name="email" placeholder="Email Address" class="form-control bg-white border-left-0 border-md">
                </div>
      
                <!-- Phone Number -->
                <div class="input-group col-lg-12 mb-4">
                  <div class="input-group-prepend">
                    <span class="input-group-text bg-white px-4 border-md border-right-0">
                      <i class="fa fa-phone-square text-muted"></i>
                    </span>
                  </div>
                  <select id="countryCode" name="countryCode" style="max-width: 80px" class="custom-select form-control bg-white border-left-0 border-md h-100 font-weight-bold text-muted">
                    <option default>+91</option>
                    
                  </select>
                  <input id="id_phone" type="tel" name="phone" placeholder="Phone Number" class="form-control bg-white border-md border-left-0 pl-3">
                </div>
    
                <div class="input-group col-lg-12 mb-4">
                  <div class="input-group-prepend">
                    <span class="input-group-text bg-white px-4 border-md border-right-0">
                      <i class="fa fa-lock text-muted"></i>
                    </span>
                  </div>
                  <input id="id_password1" type="password" name="password1" placeholder="Password" class="form-control bg-white border-left-0 border-md">
                </div>
      
                <!-- Password Confirmation -->
                <div class="input-group col-lg-12 mb-4">
                  <div class="input-group-prepend">
                    <span class="input-group-text bg-white px-4 border-md border-right-0">
                      <i class="fa fa-lock text-muted"></i>
                    </span>
                  </div>
                  <input id="id_password2" type="password" name="password2" placeholder="Confirm Password" class="form-control bg-white border-left-0 border-md">
                </div>
                
                <!-- Submit Button -->
                <div class="form-group col-lg-12 mx-auto mb-0">
                     <button type="submit" class="btn btn-primary btn-block py-2">Create your account</button> </span>
                </div>
      
                <!-- Divider Text -->
                <div class="form-group col-lg-12 mx-auto d-flex align-items-center my-4">
                  <div class="border-bottom w-100 ml-5"></div>
                  <span class="px-2 small text-muted font-weight-bold text-muted">OR</span>
                  <div class="border-bottom w-100 mr-5"></div>
                </div>
      
                <!-- Social Login -->
                <div class="form-group col-lg-12 mx-auto">
                  <a href="#" class="btn btn-primary btn-block py-2 btn-facebook">
                    <i class="fa fa-facebook-f mr-2"></i>
                    <span class="font-weight-bold">Continue with Facebook</span>
                  </a>
                  <a href="#" class="btn btn-primary btn-block py-2 btn-twitter">
                    <i class="fa fa-twitter mr-2"></i>
                    <span class="font-weight-bold">Continue with Twitter</span>
                  </a>
                </div>
      
                <!-- Already Registered -->
                <div class="text-center w-100">
                  <p class="text-white font-weight-bold">Already Registered? <a href="#" class="text-white ml-2">Login</a></p>
                </div>
      
              </div>
            </form>
          </div>
        </div>
      </div>


       {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success'%}
                <script>swal("Yuppp", "{{message}}", "success");</script>
            {% elif message.tags == 'info'%}
                <script>swal("See", "{{message}}", "info");</script>

            {% elif message.tags == 'warning'%}
                  <script>swal("Warning", "{{message}}", "warning");</script>

            {% elif message.tags == 'error'%}
                <script>swal("Oops", "{{message}}", "error");</script>
            {% endif %}
        {% endfor %}
    {% endif %}
      {% endblock content %}
        
 {% block script %}
 <script>
     // For Demo Purpose [Changing input group text on focus]
$(function () {
    $('input, select').on('focus', function () {
        $(this).parent().find('.input-group-text').css('border-color', '#80bdff');
    });
    $('input, select').on('blur', function () {
        $(this).parent().find('.input-group-text').css('border-color', '#ced4da');
    });
});

 </script>
 {% endblock script %}